Fixed PEP8 violations in code style
akshgpt7/MarvellOS pull request #37
Opened 2020-12-28 19:11 UTC by osBins

Formatted the code :
-Imported functions from the concerned modules manually.
-Fixed the conditional statements.
-Reduced line length to 79 characters per line.
-Fixed variable e assignment and defining.
to conform to PEP8 standards.

2020-12-29 02:16 UTC, akshgpt7 requested changes
Thanks for your patience on this. Good work.
Just a few changes in the review comments, mostly about `except` blocks.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +    TOP,
Try to have multiple in one line so as to not use up so many lines for imports.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +    #       except:
You don't have to comment out the except block entirely. Just find the error that it is trying to except, and except that.
If you cannot find that, last resort can be to use at least `except Exception:`.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +        if ~sh:
Use `not sh` instead of `~`.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +            stroyed"""
Just add the entire word to the new line instead of cutting it in the middle.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +    # except:
Again, don't comment out the except block, find the error to except.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +    orrect password"""
Don't cut the word in the middle

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +        # except:
Same as above except blocks.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +    # except:
Same as above.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +        if ~self.sh:
Use `not` instead of `~`.

2020-12-29 02:16 UTC, akshgpt7 commented on MarvellOS.py
> +        elif ~self.sh:
Again, use `not`.

2021-01-02 17:54 UTC, akshgpt7 requested changes
This is ready to merge, just one small last change:
Make sure all the docstrings are _after_ the function/class definition, and not before them. Eg. line 63. By convention, the docstring is written just after the line containing the `def` keyword. A few functions have it before their definition.

2021-01-02 18:14 UTC, osBins commented
I've made the required changes. I request you to let me know if there's something else that needs to be changed/formatted.

2021-01-02 18:27 UTC, akshgpt7 commented
Thanks for your patience on this. Great work!
This looks ready to merge.

2021-01-02 18:27 UTC, merged